version: "3"
services:
  anomaly-detector:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_DIR=/app/models
    restart: unless-stopped
    command: python anomaly_detector.py --api --port 5000 --model-dir /app/models
