version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=UTC
      - LOG_LEVEL=INFO
    command: >
      python app.py --api 
      --host 0.0.0.0 
      --port 5000 
      --model-dir /app/models 
      --log-level INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s